### PR TITLE
[REF] odoolint: s/unachievable/unreachable/g

### PR DESCRIPTION
**Pull request by osvalr**
The first time I heard about xml_id issues, it costed me to get what it was about. So I prefer to have **unreach** term, instead of **achieve**.

Please refer to this blog [post](http://wordcategory.blogspot.com/2012/11/difference-between-reach-and-achieve.html) that is basically my argument.

### CODE REVIEW

**Comment by moylop260** [comment]
@osvalr 
Thank you!

@oscarolar 
Could you give us your opinion?

**Comment by oscarolar** [comment]
@moylop260 
+1 to @osvalr 
- achieve an element - lograr un elemento <- _doesn't make sense._
- reach an element - llegar a un elemento.

**Comment by moylop260** [comment]
Thank you gays! (no me equivoqué)

**Comment by hbto** [comment]
> achieve an element - lograr un elemento <- doesn't make sense.
> reach an element - llegar a un elemento.

+1

**Pull request merged**
