### PR TITLE
[DUMMY] company_country: Use MX country by default

### PR DESCRIPTION
**Pull request by luisg123v**
This is intended to be used under Odoo.sh when the localization is
already installed, because environment variables are not under our
control there.

# Conflicts:
#	company_country/models/res_config.py

### CODE REVIEW

**Comment by moylop260** [comment]
@luisg123v 
I think a good change for odoosh could be skip if the module is really installed.

```patch
diff --git a/company_country/models/res_config.py b/company_country/models/res_config.py
index ab2721234..96d8f76a9 100644
--- a/company_country/models/res_config.py
+++ b/company_country/models/res_config.py
@@ -19,8 +19,11 @@ class CompanyCountryConfigSettings(models.TransientModel):
             return
         if not country_code:
             l10n_to_install = self.env['ir.module.module'].search([
-                ('state', '=', 'to install'),
-                ('name', '=like', 'l10n_%')], limit=1)
+                ('state', 'in', ('installed', 'to install'),
+                ('name', '=like', 'l10n_%')], order='state ASC', limit=1)
+            # If 1st module to-install is really installed so we don't need configure it
+            if l10n_to_install.state == 'installed':
+                return
             if not l10n_to_install:
                 raise ValidationError(
                     _('Error COUNTRY environment variable with country code '
```

**Comment by luisg123v** [comment]
@moylop260 
I like that! I'd just change the `|` operator by an `in`

I'll make the proposal.

**Comment by moylop260** [comment]
You are right!
Thanks for the proposal

**Comment by luisg123v** [comment]
I think I found a cleaner way to fix this, check https://github.com/OCA/server-tools/pull/1786

**Pull request closed without merging**
