### PR TITLE
[FIX] It avoids validating the password_history when updating the auth_crypt module.

### PR DESCRIPTION
**Pull request by egrivero**
When attempting to install the project_forecast module, a popup window is displayed with the following message: "Can not use the most recent 30 passwords" this is a message that comes from the password_security module, this occurs because it automatically updates the auth_crypt module And this module has this [init](https://github.com/Vauxoo/odoo/blob/10.0/addons/auth_crypt/models/res_users.py#L29) that updates all the users passwords, but assigning the same password, which produces a repeated password error, this if the password history is different from 0. To avoid this, use the value 'todo' Which was found in context when updating the auth_crypt module.

Tests were performed installing the module and modifying passwords, and the proposed change works

### CODE REVIEW

**Comment by egrivero** [comment]
@nhomar @moylop260  This PR is ready for review

**Comment by moylop260** [comment]
I prefer to wait @nhomar feedback

**Comment by nhomar** [comment]
@moylop260 

I was on line with @egrivero  when the patch comes on.

Basically and extending @egrivero 's answer the point is that 2 autoinstall modules comes in "auth_crypt" and "project_Forecast_Grid" and for some reason the first one is comming in "before" the pre-migration.py and the post-migration.py on our app, then, 

When we make a -u app (which do not depend of those 2 modules directly and explicitally) the update is triggered before we prepare the BD.

THe the logic is:

1.- Fix the fact that if I do not want to control the history password management then works properly (it wasn't even with 0 value it was looking in the history due to the leak of a return early) [1](https://github.com/Vauxoo/server-tools/pull/104/files#diff-3df60b05e85f13d61c9dcb913fcec212R139).
2. Using the todo: key in the context which is there only when the autoinstall is triggered then ignore any check.

But I asked to @egrivero for your opinion here.

If you think there is a different way to avoid considere the check of the "todo" key (which I could not find in any other module) I appreciate that. (I think that will be broken at test time but not sure).

Regards.

**Comment by moylop260** [comment]
@egrivero 
Could you share me the line of code where is assigned the `todo` context to be use here?

**Comment by egrivero** [comment]
@moylop260 The 'todo' key is created in this line [registry.py](https://github.com/Vauxoo/odoo/blob/10.0/odoo/modules/registry.py#L310) and used in this function [models.py](https://github.com/Vauxoo/odoo/blob/10.0/odoo/models.py#L2301). I did not find any other use that they give to that key of the context.

**Comment by moylop260** [comment]
Could you share the dummy PR where you test this behaviour from runbot?

**Comment by moylop260** [comment]
@egrivero 
I can't reproduce it

The title told us: `...updating the "auth_crypt" module...`
I just run `-u auth_crypt` from imeqmo instance and the error is not emitted

but the description told us a different step: `...installing the "project_forecast" module...`
I just run `-i project_forecast` and the error is not emitted

Do you have the issue related with our description structure (steps to reproduce it, saw, expected, video)?

If you have a PR from a project where is used from other one you will need a PR dummy to ensure that CIs aren't broken.

Could you attach a video where you tested this PR using runbot for the following test cases?
  - Error test case: Reproducing same steps but now we shouldn't emit a error.
  - Good test case: Reproducing the original behavior still working.

**Comment by egrivero** [comment]
I did not create a dummy because the error did not happen to me with data demo, but in the productive date, after talking with @moylop260 about this PR, he asked me to do a test to reproduce the error, I can not repodroute it, and then Analyze the database, I saw that the error is inherent to imeqmo.

screenshot from 2017-05-15 16 11 28

It is a mistake that there is a user who has the unencrypted key and in the 'password' field of res.users, because when auth_crypt is installed all the keys of the password field are deleted and sent to the password_crypt field, leaving the password field blank . What I have not achieved is to reproduce how they achieved that, I created users from the website and created users in back-end, and I did not achieve that. Although I'm sure the user had to be created from the website.

I think that with this information, this PR is not necessary, since this allowed me to realize that there was a user with an incorrect value in the database. I think that the user who has password without encryption in the instance must be corrected.

Now the doubt I have is whether it should be functionally corrected by changing the user's password or should it be corrected with a script? I say this because the way that I got that I got the password was corrected, it was changing the password of the user

**Comment by egrivero** [comment]
@moylop260 
Add a test of how the error should be. And a dummy here vauxoo/imeqmo#141

**Comment by nhomar** [comment]
On Tue, May 16, 2017 at 8:00 AM, Edgar Rivero [Vauxoo] <
notifications@github.com> wrote:

> Now the doubt I have is whether it should be functionally corrected by
> changing the user's password or should it be corrected with a script? I say
> this because the way that I got that I got the password was corrected, it
> was changing the password of the user


It brings me an alert.....

Checking into production.

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by moylop260** [comment]
Fixed from https://github.com/OCA/server-tools/pull/859 and updated from https://github.com/Vauxoo/server-tools/pull/110

**Pull request closed without merging**
